AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Session Functions

Parameters:
  Environment:
    Type: String
    Default: "default"
    AllowedValues:
      - prod
      - dev
      - default
  OpenF1BaseUrl:
    Type: String
    Default: "https://api.openf1.org/v1"

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256

Resources:
  F1ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "F1Api-${Environment}"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  RawDataIngestion:
      Type: AWS::Serverless::Function
      Properties:
        Handler: raw_data_ingestion.handler
        CodeUri: ./lambda/data_ingestion
        Policies:
          - AWSLambdaBasicExecutionRole
          - S3CrudPolicy:
              BucketName: !Ref RawDataBucket
        Environment:
          Variables:
            S3_BUCKET: !Ref RawDataBucket
            OPENF1_BASE_URL: !Ref OpenF1BaseUrl
        Timeout: 120
        Events:
          DataIngest:
            Type: Api
            Properties:
              RestApiId: !Ref F1ApiGateway
              Path: /data-ingestion
              Method: POST

  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "raw-data-bucket-${Environment}"

  ProcessSession:
    Type: AWS::Serverless::Function
    Properties:
      Handler: process_session.handler
      CodeUri: ./lambda/data_ingestion
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref RawDataBucket
      Environment:
        Variables:
          S3_BUCKET: !Ref RawDataBucket
          DYNAMODB_TABLE: !Ref OpenF1Table
      Timeout: 120
      Events:
        ProcessSession:
          Type: Api
          Properties:
            RestApiId: !Ref F1ApiGateway
            Path: /process-session
            Method: PATCH

  OpenF1Table:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "f1-sessions-data-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  IngestEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - raw.data.ingest
        detail-type:
          - json.ingested
      Targets:
        - Arn: !GetAtt ProcessSession.Arn
          Id: ProcessLambdaTarget


#  GetSession:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: get_session.handler
#      CodeUri: ./lambda/session_functions/get_session
#      Policies:
#        - AWSLambdaBasicExecutionRole
#      Events:
#        AddUser:
#          Type: Api
#          Properties:
#            RestApiId: !Ref F1ApiGateway
#            Path: /sessions
#            Method: GET
#
#  ListDrivers:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: list_drivers.handler
#      CodeUri: ./lambda/session_functions/list_drivers
#      Policies:
#        - AWSLambdaBasicExecutionRole
#      Events:
#        ListDrivers:
#          Type: Api
#          Properties:
#            RestApiId: !Ref F1ApiGateway
#            Path: /drivers
#            Method: GET
