AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Session Functions

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256

Resources:
  GetSession:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_session.handler
      CodeUri: ./get_session
      Environment:
        Variables:
          SESSION_KEY: 9205
      Policies:
        - AWSLambdaBasicExecutionRole
